In [1]:
!pip install nptyping

In [3]:
!pip install beartype

  Obtaining dependency information for beartype from https://files.pythonhosted.org/packages/46/8a/a90fe78c73958340ed6b6ab128a10598ad5f0ff57537ad17f6ccd1ad830b/beartype-0.16.4-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/819.1 kB ? eta -:--:--
   -- ------------------------------------- 41.0/819.1 kB ? eta -:--:--
   -- ------------------------------------- 41.0/819.1 kB ? eta -:--:--
   -- ------------------------------------ 61.4/819.1 kB 469.7 kB/s eta 0:00:02
   --- ----------------------------------- 81.9/819.1 kB 459.5 kB/s eta 0:00:02
   ---- ---------------------------------- 92.2/819.1 kB 435.7 kB/s eta 0:00:02
   ----- -------------------------------- 122.9/819.1 kB 450.6 kB/s eta 0:00:02
   ------ ------------------------------- 143.4/819.1 kB 448.2 kB/s eta 0:00:02
   ------ ------------------------------- 143.4/819.1 kB 448.2 kB/s eta 0:00:02
   ------ ------------------------------- 143.4/819.1 kB 448.2 kB/s eta 0:00:02
   --------- ----------

## Scalar Type

In [1]:
import numpy as np
a: np.ndarray = np.array(1000) # object array
display(a)
display(type(a))
display(a.shape) 
display(a.dtype)
display(a.ndim)
display(a.size)
display(a.itemsize)


array(1000)

numpy.ndarray

()

dtype('int32')

0

1

4

## Vector Type

In [7]:
import numpy as np
a: np.ndarray = np.array([1, 2, 3, 4, 5]) # object array
display(a)
display(type(a))
display(a.shape) 
display(a.dtype)
display(a.ndim)
display(a.size)
display(a.itemsize)


array([1, 2, 3, 4, 5])

numpy.ndarray

(5,)

dtype('int32')

1

5

4

## Matric Type

In [10]:
import numpy as np
data = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
a: np.ndarray = np.array(data) # object array
display(a)
display(type(a))
display(a.shape) 
display(a.dtype)
display(a.ndim)
display(a.size)
display(a.itemsize)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

numpy.ndarray

(3, 4)

dtype('int32')

2

12

4

# Numpy with NDArray typing support

In [21]:
import numpy as np
from nptyping import NDArray, Shape, UInt32
from typing import Any
data: NDArray[Shape["10"], Any] = np.arange(1, 11)
print(data)
print(type(data))
print(data + 7)

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
[ 8  9 10 11 12 13 14 15 16 17]


In [12]:
data_raw: list[int] = [1, 2, 3, 4, 5]
data_raw + 5


TypeError: can only concatenate list (not "int") to list

In [13]:
[i + 5 for i in data_raw]

[6, 7, 8, 9, 10]

In [18]:
data_large: list[int] = list(range(1, 1000000))
data_large + 5

TypeError: can only concatenate list (not "int") to list

In [19]:
%%time
[i + 5 for i in data_large]

CPU times: total: 109 ms
Wall time: 159 ms


[6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,


# numpy advanced operations vs list operations

In [2]:
data1: list[int] = list(range(1, 21))
print(data1)
print(data1[5:11])
data1[5:11] = 1000

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11]


TypeError: can only assign an iterable

In [5]:
import numpy as np
from nptyping import NDArray, Shape, UInt32
from typing import Any
ndata: NDArray[Shape["20"], Any] = np.arange(1, 21)
print(ndata)
print(ndata[5:11])
ndata[5:11] = 1000
print(ndata)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11]
[   1    2    3    4    5 1000 1000 1000 1000 1000 1000   12   13   14
   15   16   17   18   19   20]


# Numpy id Functions

In [12]:
state_bank: NDArray[Shape["10"], Any] = np.array([1, 7, 8, 10])
display(state_bank)
state_bank % 2 == 0

array([ 1,  7,  8, 10])

array([False, False,  True,  True])

In [13]:
state_bank[state_bank % 2 == 0]

array([ 8, 10])

In [14]:
from nptyping import Bool
state_bank: NDArray[Shape["10"], Any] = np.array([1, 7, 8, 10])
selection: NDArray[Shape["10"], Bool] = np.array([True, False, False, True])
state_bank[selection]

array([ 1, 10])

In [15]:
state_bank: NDArray[Shape["10"], Any] = np.array([1, 7, 8, 10])
ubl_bank: NDArray[Shape["20"], Any] = np.random.randint(0, 100, 20)
display(state_bank)
display(ubl_bank)

array([ 1,  7,  8, 10])

array([61, 40,  1, 99, 20, 34, 47, 84, 67, 19, 41, 10, 87, 73, 20, 33, 13,
        2, 26, 23])

In [18]:
np.in1d(state_bank, ubl_bank)

array([ True, False, False,  True])

In [19]:
state_bank[np.in1d(state_bank, ubl_bank)]

array([ 1, 10])

In [20]:
np.intersect1d(state_bank, ubl_bank)

array([ 1, 10])

In [27]:
x: NDArray[Shape["5"], Any] = np.array([1, 3, 4, 5, 7])
y: NDArray[Shape["5"], Any] = np.array([6, 4, 2, 5, 9])
display(x)
display(y)
np.where(x > y, x, y)

array([1, 3, 4, 5, 7])

array([6, 4, 2, 5, 9])

array([6, 4, 4, 5, 9])

# Creating Numpy Array

In [33]:
sample: NDArray[Shape["Size, Size"], Any] = np.array([[1, 2, 3], [4, 5, 6]])
print(sample)
sample: NDArray[Shape["Size, Size"], Any] = np.array([[1, 3], [4, 6]])
print(sample)
sample: NDArray[Shape["Size, Size"], Any] = np.array([[3], [4]])
print(sample)

[[1 2 3]
 [4 5 6]]
[[1 3]
 [4 6]]
[[3]
 [4]]


In [35]:
sample: NDArray[Shape["*, *"], Any] = np.array([[1, 2, 3], [4, 5, 6]])
print(sample)
sample: NDArray[Shape["*, *"], Any] = np.array([[1, 3], [4, 6]])
print(sample)
sample: NDArray[Shape["*, *"], Any] = np.array([[3], [4]])
print(sample)

[[1 2 3]
 [4 5 6]]
[[1 3]
 [4 6]]
[[3]
 [4]]


In [36]:
np.who()

Name            Shape            Bytes            Type

_               5                20               int32
__              5                20               int32
___             5                20               int32
ndata           20               80               int32
state_bank      4                16               int32
ubl_bank        20               80               int32
selection       4                4                bool
_10             2                8                int32
_12             4                4                bool
_13             2                8                int32
_14             2                8                int32
_16             4                4                bool
_17             2                8                int32
_18             4                4                bool
_19             2                8                int32
_20             2                8                int32
x               5                20               in

In [38]:
# 1d array
s_array: NDArray[Shape["Size"], Any] = np.arange(1, 6)
display(s_array)

s_array: NDArray[Shape["Size"], Any] = np.arange(1, 11)
display(s_array)

array([1, 2, 3, 4, 5])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
# 2d array
s_array: NDArray[Shape["Size, Size"], Any] = np.arange(3*3).reshape(3, 3)
display(s_array)

s_array: NDArray[Shape["Size, Size"], Any] = np.arange(5*3).reshape(5, 3)
display(s_array)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [42]:
# 3d array
s_array: NDArray[Shape["Size, Size, Size"], Any] = np.arange(2*3*3).reshape(2, 3, 3)
display(s_array)

s_array: NDArray[Shape["Size, Size, Size"], Any] = np.arange(2*5*3).reshape(2, 5, 3)
display(s_array)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [43]:
np.asarray([1, 2, 3])

array([1, 2, 3])

In [44]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [45]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [51]:
s_array: NDArray[Shape["Size, Size, Size"], Any] = np.arange(2*5*3).reshape(2, 5, 3)
np.ones_like(s_array)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [55]:
s_array: NDArray[Shape["Size, Size, Size"], Any] = np.arange(5*2*2).reshape(5, 2, 2)
s_array[[0, -1], ::, ::]

array([[[ 0,  1],
        [ 2,  3]],

       [[16, 17],
        [18, 19]]])

In [61]:
raw_data: NDArray[Shape["20"], Any] = np.arange(1, 21)
print(raw_data)
print(raw_data.min())
print(raw_data.argmin())
print(raw_data.max())
print(raw_data.argmax())
print(raw_data.mean())
print(raw_data.std())
print(raw_data.sum())
print(raw_data.prod())
print(raw_data.cumsum())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
0
20
19
10.5
5.766281297335398
210
-2102132736
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210]
